set_property(TARGET ${PROJECT_NAME} PROPERTY CXX_STANDARD 17)
if ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU")
    set(PRIVATEOPTS -Wall -Wextra -Werror -Wshadow)
    if ("${CMAKE_BUILD_TYPE}" STREQUAL "Release")
        set(PRIVATELINKOPTS LINKER:-s)
    endif()
elseif("${CMAKE_CXX_COMPILER_ID}" STREQUAL "MSVC")
    set(PRIVATEOPTS /W3)
endif()
target_compile_options(${PROJECT_NAME} PRIVATE ${PRIVATEOPTS})
target_link_options(${PROJECT_NAME} PRIVATE ${PRIVATELINKOPTS})
